students:
  workbook: examples/student_sheet.xlsx
  sheet: Students
  info:
    - col: A
      key: Student ID
    - col: B
      key: Last Name
    - col: C
      key: Pref Name
  output: data/{info[Pref Name]} {info[Last Name]}__{info[Student ID]}.xlsx

questions:
  workbook: examples/question_sheet.xlsx
  sheet: QuestionBank
  question_cols: ABCD
  question_height: 5
  difficulty_col: E
  tags_cols: FGHIJ
  indexing_col: N

template:
  workbook: examples/interview_template.xlsx
  computed_cols:
    - key: "I10"
      expr: "{info[Pref Name]} {info[Last Name]} - {info[Student ID]}"
      sheet: rubric
  question_sheet: Questions
  question_locations:
    - "G2"
    - "L2"
    - "B8"
    - "G8"
    - "L8"
  rubric_sheet: Rubric
  rubric_locations:
    - "B2"
    - "B3"
    - "B4"
    - "B5"
    - "B6"

randomisation:
  choices: examples/choices.yml
  selection:
    min_diff: 9
    max_diff: 11
    required_tags: FGHI

images:
  examples/images/excel.png:
    preffered_width: 150
    offset_x: 0.3
    offset_y: -0.3
  examples/images/b1.jpg:
    preffered_height: 200
    offset_x: 0.4
    offset_y: -0.35
  examples/images/b2.jpg:
    preffered_height: 200
    offset_x: 0.4
    offset_y: -0.35
