students:
  workbook: examples/student_sheet.xlsx
  sheet: Students
  info:
    - col: A
      key: Student ID
    - col: B
      key: Last Name
    - col: C
      key: Pref Name
  output: data/{info[Pref Name]} {info[Last Name]}__{info[Student ID]}.xlsx

questions:
  workbook: examples/question_sheet.xlsx
  sheet: QuestionBank
  question_cols: ABCD
  question_height: 5
  difficulty_col: E
  tags_cols: FGHIJ
  indexing_col: N

template:
  workbook: examples/interview_template.xlsx
  question_sheet: Questions
  question_locations:
    - "G2"
    - "L2"
    - "B8"
    - "G8"
    - "L8"
  rubric_sheet: Rubric
  rubric_locations:
    - "B2"
    - "B3"
    - "B4"
    - "B5"
    - "B6"

randomisation:
  choices: examples/choices.yml
  selection:
    min_diff: 9
    max_diff: 11
    required_tags: FGHI
